highlighter: pygment
markdown: kramdown
future: false

# Enable sass
sass:
    style: compressed
 
languages:          ['it']
language_default:   'it'

default_locale: "it" 

# site Name
name: "Web Pilates"

# site Menu [ [ neme_link, absolute_path ], ... ]
menu: [["home", "/" ], ["eventi", "/events/"], ["blog", "/blog/"]]

# even without a web server
index: "index.html"

# events
collections:
  events:
    output: true

